// Code generated by jtd-codegen for TypeScript v0.2.1

export interface SyntaxGrammar {
  desc: string;
  is: string;
  name: string;
  where?: { [key: string]: string };
}

export interface Syntax {
  desc: string;
  grammar: SyntaxGrammar[];
  suggest: string[];
}
