// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Query {
  args: Term[];
  literals: { [key: string]: TexMath };
  max_results: number;
  relation: Identifier;
  variables: { [key: string]: TexMath };
}

export type Identifier = string;

export type Term = TermCon | TermRef;

export interface TermCon {
  is: "con";
  args: Term[];
  tag: Identifier;
}

export interface TermRef {
  is: "ref";
  to: Identifier;
}

export type TexMath = string;
