// Code generated by jtd-codegen for TypeScript v0.2.1

export interface SystemRelationRulePremise {
  args: Term[];
  relation: Identifier;
}

export interface SystemRelationRuleRule {
  id: Identifier;
  tex: TexText;
}

export interface SystemRelationRule {
  literals: { [key: string]: TexMath };
  patterns: { [key: string]: Term };
  premises: SystemRelationRulePremise[];
  rule: SystemRelationRuleRule;
  variables: { [key: string]: TexMath };
}

export interface SystemRelation {
  arguments: Arguments;
  description: TexText;
  fixity: Fixity;
  rules: SystemRelationRule[];
  tex_parts: TexMathParts;
}

export interface SystemSyntaxGrammar {
  arguments: Arguments;
  description: TexText;
  fixity: Fixity;
  id: Identifier;
  tex_parts: TexMathParts;
}

export interface SystemSyntax {
  description: TexText;
  grammar: SystemSyntaxGrammar[];
  suggestions: TexMath[];
}

export interface System {
  description: TexText;
  relations: { [key: string]: SystemRelation };
  syntax: { [key: string]: SystemSyntax };
}

export interface Argument {
  from: Identifier;
  id: Identifier;
  tex: TexMath;
}

export type Arguments = Argument[];

export enum Fixity {
  Infix = "infix",
  None = "none",
  Postfix = "postfix",
  Prefix = "prefix",
}

export type Identifier = string;

export type Term = TermCon | TermRef;

export interface TermCon {
  is: "con";
  args: Term[];
  from: Identifier;
  tag: Identifier;
}

export interface TermRef {
  is: "ref";
  to: Identifier;
}

export type TexMath = string;

export type TexMathParts = TexMath[];

export type TexText = string;
