// Code generated by jtd-codegen for TypeScript v0.2.1

export type DerivationTree = Derivation[];

export interface Derivation {
  args: DerivationTerm[];
  premises: Derivation[];
  relation: Identifier;
  rule: Identifier;
}

export type DerivationTerm = DerivationTermCon | DerivationTermLit | DerivationTermVar;

export interface DerivationTermCon {
  is: 'con';
  args: DerivationTerm[];
  from: Identifier;
  tag: Identifier;
}

export interface DerivationTermLit {
  is: 'lit';
  id: Identifier;
}

export interface DerivationTermVar {
  is: 'var';
  counter: number;
  id: Identifier;
}

export type Identifier = string;
